### ISSUE TITLE
Figure L curves

### ISSUE THREAD

**Issue by ccluri** [Neuroinflab/kCSD-python#74]
![fig1_lcurve](https://user-images.githubusercontent.com/546703/51312035-41771e00-1a42-11e9-8632-3d3c973274e7.jpg)

1) Remove splines on top and right for all the figures
2) Remove box around the legend - it legend should be below the figures, without a bounding box.
3) Follow the https://github.com/Neuroinflab/kCSD-python/blob/master/figures/kCSD_properties/figure_properties.py and use gridspec as in https://github.com/Neuroinflab/kCSD-python/blob/master/figures/kCSD_properties/figure_vectors.py - consistency in font size and font styles across all figures in the paper.
4) Recommend rearranging so that Topleft is potentials, bottom left is truecsd/ kCSD, top right is L curve bottom right is CV. 
5) Increase the gap between the rows of the figure
6) Align the y-axis labels
7) Increase the resolution to 300 dpi

![fig2_lcurve](https://user-images.githubusercontent.com/546703/51312398-1b9e4900-1a43-11e9-8809-7faa71ea0d9f.jpg)

0) Use figure properties and gridspec as above
1) Remove splines top and right for both subplots. Top subplot has a shared x-axis with the bottom - consider something like figure_vectors.py where only the last row has the necessary x-axis units and labels.
2) Legend must be below the figures, without a bounding box.
3) Align the y axis labels.

![fig3_lcurvea](https://user-images.githubusercontent.com/546703/51312629-a3845300-1a43-11e9-81e3-7325ef2d1054.jpg)
1) Why does the cbar here have both positive and negative values when the countour has only positive values? Move the cbar below, like in the error map figures. 
2) For this subplot 1 and 2 - combine these into one figure - use gridspect and figure properties for the font size and font styles.

![fig3_lcurveb](https://user-images.githubusercontent.com/546703/51312824-14c40600-1a44-11e9-9a06-88af88b9949b.jpg)
1) Move cbar below the figure. 
2) The red-ellipse is not as apparent.

**Comment by ccluri** [comment]
@wsredniawa

**Comment by ccluri** [comment]
Traceback (most recent call last):
  File "kCSD1D_test_fig1_and_fig2_v2.py", line 357, in <module>
    sim_results = np.load('sim_results.npy')
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'sim_results.npy'


#79 fails to run. Please check the file names and the folders to see the updated files are being used instead of the previously generated sim_results.npy
